Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> The first part of this CL looks ok (carchive test fix).
> 
> I am not clear on the need for the second change-- it seems that shared libgo is counting on this. Example:
> 
> $ go env GOROOT
> /tmp/install.relwithdbg
> $ llvm-goc -L /tmp/install.relwithdbg/lib64 himom.go -o himom
> $ ldd himom | fgrep libgo.so
> 	libgo.so.10git => /tmp/install.relwithdbg/lib64/libgo.so.10git (0x00007f2bb1bc5000)
> $ objdump -t /tmp/install.relwithdbg/lib64/libgo.so.10git | fgrep pthread_create
> 0000000000f747b0 l     F .text	000000000000008b              __wrap_pthread_create
> 0000000000000000  w    F *UND*	0000000000000000              pthread_create@@GLIBC_2.2.5
> $ 
> 
> Could you say a bit more about why we shouldn't be using --wrap?

I found this error “undefined reference to '__wrap_pthread_create'” when debugging some test failures of the Go standard libraries. Then found this linker option. I'm not familiar with the meaning of this option, this document https://ftp.gnu.org/old-gnu/Manuals/ld-2.9.1/html_node/ld_3.html says that we can use this option when we wrap some system functions, but I did not find the function __pthread_create that wraps the pthread_create function in the gollvm code. When I removed this option, all unit tests and standard library tests pass, so I thought this option was redundant. I don't know if it is used in a specific scenario? shared library? I don't know how to construct such a case.

Patch-set: 1